# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0007_auto_20170504_2230'),
        ('DocCreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedTime', models.DateTimeField(auto_now=True)),
                ('selected', models.BooleanField(default=False)),
                ('urlDoc', models.CharField(max_length=200)),
                ('generatedDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocCreator.GeneratedDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdTime', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
        migrations.AddField(
            model_name='attacheddoc',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Missions.Mission'),
        ),
    ]
