# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacheddoc',
            name='generatedDoc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='DocCreator.GeneratedDoc'),
        ),
        migrations.AlterField(
            model_name='attacheddoc',
            name='urlDoc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
