# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0002_auto_20170504_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Missions.Mission')),
            ],
        ),
    ]
