# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0003_missionfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionfield',
            name='createdTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='missionfield',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attacheddoc',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
