# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0005_auto_20170517_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacheddoc',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
