# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0007_auto_20170517_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
