# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0008_mission_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='lastmodifTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 13, 49, 26, 263636)),
        ),
    ]
