# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=200)),
                ('invalidationDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users'),
        ),
    ]
