# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_logdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.Users'),
        ),
    ]
