# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20170504_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
