# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_logdata_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Cellphone',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Cellphone',
            new_name='cellphone',
        ),
    ]
