# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20170504_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='siret',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
