# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_client_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
